#!/usr/bin/env bash

# Check if a host is on the network by pinging it
host=$1

if [[ -z "$host" ]]; then
    echo "Please provide a host."
    exit 1
fi

ping -c 1 "$host" &> /dev/null

if [[ $? -eq 0 ]]; then
    echo "$host is up."
else
    echo "$host is down."
fi
