#!/usr/bin/env bash
# this script will change your home IP address to localhost and fcebook

# backup the hosts file
cp /etc/hosts /etc/hosts.bak


# change the IP address in the hosts file and facebook
sed -i '/127.0.0.1\s\+localhost/s/^/#/' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

sed -i '/faceboock.com/s/^/#/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts


ping -c 1 localhost
ping -c 1 facebook.com


echo "configuration complete. /etc/hosts file has been updated"

